faiss_db:
  collection_name: "document_portal"

embedding_model:
  provider: "openai"
  model_name : "text-embedding-3-large"

retriever:
  top_k : 10

llm:
  openai:
    model_name: "gpt-4o-mini"
    temperature: 0.0
    max_output_tokens: 4096

  google:
    model_name: "gemini-1.5-flash"
    temperature: 0.0
    max_output_tokens: 4096
